Numpy

In [1]:
import numpy as np

In [2]:
numbers = np.array([10, 20, 30, 40, 50])
print (numbers)

[10 20 30 40 50]


1D Array

In [3]:
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [4]:
print(np.ndim(arr))

1


In [5]:
print(np.sum(arr))

100


In [6]:
print(np.max(arr))

40


In [7]:
arr1= arr+50
print(arr1)

[60 70 80 90]


In [8]:
arr2= arr*2
print(arr2)

[20 40 60 80]


2d array

In [9]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(np.size(arr_2d))

9


In [11]:
print(np.shape(arr_2d))

(3, 3)


In [12]:
arr2d = np.array([[10,20,30],
                  [40,50,60],
                  [70,80,90]])
print(arr2d)
print(np.ndim(arr2d))
print(np.shape(arr2d))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
2
(3, 3)


Q1: 20 nikalo
Q2: 60 nikalo
Q3: 70 nikalo
Q4: 90 nikalo

In [13]:
print(arr2d[0,1])
print(arr2d[1,2])
print(arr2d[2,0])
print(arr2d[2,2])
print(arr2d[1])

20
60
70
90
[40 50 60]


Zeros

In [14]:
arr_zero = np.zeros((5,5))
print(arr_zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
print(np.ndim(arr_zero))

2


Ones

In [16]:
arr_ones = np.ones((3,5))
print(arr_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


full

In [17]:
arr_full = np.full((3,3),6)
print(arr_full)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


Arange

In [18]:
arr_arange = np.arange(1,11,3)
print(arr_arange)

[ 1  4  7 10]


identity matrix

In [19]:
np_eye = np.eye(5)
print(np_eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


3D Array

In [20]:
arr_3d = np.array([[[1,2,3.6],
                    [4,5,6],
                    [7,8,9]],
                    [[10,20,30],
                     [40,50,60],
                     [70,80,90]]])
print(arr_3d)
print(np.ndim(arr_3d))
print(np.shape(arr_3d))

[[[ 1.   2.   3.6]
  [ 4.   5.   6. ]
  [ 7.   8.   9. ]]

 [[10.  20.  30. ]
  [40.  50.  60. ]
  [70.  80.  90. ]]]
3
(2, 3, 3)


In [21]:
print(arr_3d.dtype)

float64


In [22]:
arr3d = arr_3d.astype(int)
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


Functions

In [23]:
array  = np.array([10,20,30,40,50,60,70])

print("Addition - ",np.add(array,10))
print("Subtract -",np.subtract(array,5))
print("Multiply - ",np.multiply(array ,2))
print("divide - ",np.divide(array,2))
print("Power -",np.power(array,2))
print("mod - ",np.mod(array,3))
print("Sum -",np.sum(array))
print("mean - ",np.mean(array))
print("min -",np.min(array))
print("max - ",np.max(array))
print("Standard Deviation -",np.std(array))
print("Variance - ",np.var(array))
print("Median - ",np.median(array))

Addition -  [20 30 40 50 60 70 80]
Subtract - [ 5 15 25 35 45 55 65]
Multiply -  [ 20  40  60  80 100 120 140]
divide -  [ 5. 10. 15. 20. 25. 30. 35.]
Power - [ 100  400  900 1600 2500 3600 4900]
mod -  [1 2 0 1 2 0 1]
Sum - 280
mean -  40.0
min - 10
max -  70
Standard Deviation - 20.0
Variance -  400.0
Median -  40.0


Slicing

In [24]:
a = np.array([1,3,4,5,6,7,8,3,4])

print(a[0])
print(a[1:4])
print(a[::2])
print(a[::-1])

1
[3 4 5]
[1 4 6 8 4]
[4 3 8 7 6 5 4 3 1]


filtering

In [25]:
a = np.array([1,3,4,5,6,7,8,3,4])

print(a[a>3])
print(a[a<5])
print(a[a>=5])
print(a[a<=3])
print(a[a%2==0])
print(a[(a>=3) & (a<=7) ])

[4 5 6 7 8 4]
[1 3 4 3 4]
[5 6 7 8]
[1 3 3]
[4 6 8 4]
[3 4 5 6 7 3 4]


fancy indexing

In [26]:
b = np.array([10,20,30,40,50,60,70])
print(b[[1,2,3]])

[20 30 40]


Reshaping & Manipulating Arrays

In [27]:
# reshape(rows, columns) specify new shape. If dimensions match

a = np.array([1,2,3,4,5,6])
reshape_a = a.reshape(3,2)
print(reshape_a)
print(a.reshape(2,3))

#flatten - copy   always return a copy
#ravel - view    returns a view whenever a possible

arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d.ravel())
print(arr2d.flatten())

arr_d = np.array ([[[10,20,30]],[[40,50,60]]])
print(arr_d.ravel())

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[10 20 30 40 50 60]


Array Modification

In [28]:
c = np.array([1,2,3,4,5,6,7,8,9])
print(np.insert(c,4,100))

c2d = np.array([[10,20,30],[40,50,60]])
print(np.insert(c2d ,2,[70,80,90],axis=0))

[  1   2   3   4 100   5   6   7   8   9]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [29]:
d = np.array([23,4,5,34,65])
print(np.append(d,[34,5,6]))

[23  4  5 34 65 34  5  6]


In [30]:
x= np.array([1,2,3])
y = np.array([4,5,6])
xy = np.concatenate((x,y))
print(xy)

[1 2 3 4 5 6]


In [31]:
u = np.array([23,4,5,34,65])
print(np.delete(u,2))


[23  4 34 65]


axis 0/1

In [32]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))
print(np.mean(a, axis=0))

[50 70 90]
[ 60 150]
[25. 35. 45.]


vstack()
hstack()

In [33]:
x= np.array([1,2,3])
y = np.array([4,5,6])

print(np.vstack((x,y)))
print(np.hstack((x,y)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


split() hsplit() vsplit()

In [34]:
b = np.array([10,20,30,40,50,60,70,80])
c= np.array([[10,20,30,90],[40,50,60,70]])
print(np.split(b,4))
print(np.hsplit(b,2))
print(np.vsplit(c,2))

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]
[array([10, 20, 30, 40]), array([50, 60, 70, 80])]
[array([[10, 20, 30, 90]]), array([[40, 50, 60, 70]])]


Broadcasting & Vectorisation

In [35]:
price = np.array([100,200,300,400])
discount= 15  # % 

final_price = price-(price*discount/100)
print(final_price)

[ 85. 170. 255. 340.]


In [36]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([7,8,9])
print(matrix+vector)

[[ 8 10 12]
 [11 13 15]]


In [37]:
"""
np.isnan
np.nan_to_num()
np.isinf()
"""

'\nnp.isnan\nnp.nan_to_num()\nnp.isinf()\n'

In [38]:
np.random.seed(42)

print(np.random.randint(1, 10, 5))

[7 4 8 5 7]


In [39]:
print(np.random.rand(5))
print(np.random.randint(1,101,10))
print(np.random.randint(1,51,(3,4)))
a = np.array([10,20,30,40,50])
print(np.random.choice(a,3))


[0.44583275 0.09997492 0.45924889 0.33370861 0.14286682]
[ 3 22 53  2 88 30 38  2 64 60]
[[21 33 12 22]
 [44 25 49 27]
 [42 28 16 15]]
[30 40 40]


In [40]:
np.random.seed(42)
print(np.random.randint(1,10,5))

[7 4 8 5 7]


# More things will be added in the future.
